//Next JS imports
import Head from "next/head";

//React import
import { useState, useEffect } from "react";

//Near imports
import { signIn, signOut, wallet } from "../near/near-setup";

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    if (wallet.getAccountId()) {
      setUser(wallet.getAccountId());
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Next JS-Near Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main-div">
        {!user ? (
          <>
            <h4>This is a Near Api template for Next JS</h4>
            <button
              className="button"
              onClick={() => {
                signIn();
              }}
            >
              Sign In
            </button>
          </>
        ) : (
          <>
            <h4>Welcome {user}</h4>
            <button
              className="button"
              onClick={() => {
                signOut();
                setUser(null);
              }}
            >
              Sign out
            </button>
          </>
        )}
      </div>
    </div>
  );
}
